# Generated by Django 4.2 on 2025-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScannedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_phishing", models.BooleanField(default=False)),
                ("is_fraud", models.BooleanField(default=False)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
